name: Deploy

on:
  push:
    branches:
      - main
      - "github-actions-to-deploy"
  pull_request:
    branches:
      - main
      - "github-actions-to-deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://danielcosta.info/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy file via SSH key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "."
          tar_tmp_path: "/home/${{ secrets.SSH_USERNAME }}/site.tmp/"
          target: "${{ secrets.TARGET_DIRECTORY }}"
          rm: true
          debug: true
